<?php

/**
 * BaseExampleComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $example_id
 * @property integer $comment_id
 * @property Example $Example
 * @property Comment $Comment
 * 
 * @method integer        getExampleId()  Returns the current record's "example_id" value
 * @method integer        getCommentId()  Returns the current record's "comment_id" value
 * @method Example        getExample()    Returns the current record's "Example" value
 * @method Comment        getComment()    Returns the current record's "Comment" value
 * @method ExampleComment setExampleId()  Sets the current record's "example_id" value
 * @method ExampleComment setCommentId()  Sets the current record's "comment_id" value
 * @method ExampleComment setExample()    Sets the current record's "Example" value
 * @method ExampleComment setComment()    Sets the current record's "Comment" value
 * 
 * @package    byexample
 * @subpackage model
 * @author     koralgol
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExampleComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('example_has_comment');
        $this->hasColumn('example_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('comment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Example', array(
             'local' => 'example_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Comment', array(
             'local' => 'comment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}