<?php

/**
 * HintTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HintTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HintTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Hint');
    }
}